#You can find SID in your Twilio Dashboard
SID = 'AC84ae5eceXXXXXXXXXXXXX6ff711b05'
 
#You can find AUTH_TOKEN in your Twilio Dashboard
AUTH_TOKEN = 'cd2f5435XXXXXXXXXXXXXb29bbb1'

#FROM_NUMBER, This is the number generated by Twilio. 
FROM_NUMBER = '+12XXXXXXX73'

#TO_NUMBER, this is your number
TO_NUMBER = '+9174XXXXXX54'

#You can find API_KEY in your Boltiot Cloud
API_KEY = 'd5745340-XXXXXXXXXXXXXXX-c12dfc9ff1c8'

#You can find DEVICE_ID in your Boltiot Cloud
DEVICE_ID = 'BOLTXXXXX165'